site_name: Open Transformation Playbooks
theme:
  name: material

repo_name: 'GitHub'
repo_url: 'https://github.com/TransformationPlaybooks/playbooks'

docs_dir: 'docs'
# we're using "main" as the default branch
edit_uri: 'edit/main/docs/'

# Page tree
nav:
  - 'index.md'
  - 'Open Transformation Playbooks' :
    - 'The Purpose of Organizational Design' : 'purpose_of_organizational_design.md' 
    - 'Language' :
      - 'About language and taxonomy' : 'language/language.md' 
      - 'People and Groupings' : 'language/language-people-and-groupings.md'
      - 'Business' : 'language/language-business.md'
    - 'Goals' : 'goals.md'
    - 'Design' :
      - 'The Designing of the Organization' : 'design/designing-of-the-organization.md'
      - 'Demand Side' :
        - 'Demand Activity Plays' : 'design/demand/demand-activity-plays.md'
        - 'Demand Design Consideration and Concepts' : 'design/demand/demand-design-considerations-and-concepts.md'
        - 'Demand Delivery - Teams and Roles in Depth' : 'design/demand/demand-delivery_teams-and-roles-in-depth.md'
        - 'Team Design Considerations' : 'design/demand/team-design-considerations.md'
      - 'Supply Side' :
        - 'Supply Activity Plays' : 'design/supply/supply-activity-plays.md'
        - 'Supply Design Considerations' : 'design/supply/supply-design-considerations.md'
        - 'Supply - Talent Pools and Roles in Depth' : 'design/supply/supply-talent-pools-and-roles-in-depth.md'
      - 'Learn and Enhance' : 'design/learn-and-enhance.md'
      - 'Reporting' : 'design/reporting/reporting.md'
    - 'Helper Templates' :
      - 'About Templates' : 'template/templates.md'
      - 'Talent Pool Definition Card' : 'template/template-talent-pool-definitions.md'
      - 'Delivery Gorup Definition Card' : 'template/template-delivery-group-definition.md'
      - 'Accelerator Enablers' : 'template/template-accelerators-enablers.md'
    - 'Future Expansion Points' :
      - 'Why Transform?' : 'future-expansion-points/why-transform.md'
    - 'References' : 'references.md'





## Sample config file from https://betterprogramming.pub/build-a-blog-with-github-and-mkdocs-cf47914affa7
#
# site_name: Al-waleed Shihadeh
# site_description: Al-waleed Shihadeh
# site_author: wshihadeh
# site_url: https://wshihadeh.github.io
# dev_addr: 0.0.0.0:8000

# repo_name: 'GitHub'
# repo_url: 'https://github.com/wshihadeh/wshihadeh.github.io'

# docs_dir: 'docs'
# edit_uri: 'edit/source/docs/content/'

# # https://squidfunk.github.io/mkdocs-material/
# theme:
#   name: 'material'
#   custom_dir: 'theme'
#   language: en
#   include_sidebar: true
#   #favicon: assets/img/icon.png
#   #logo: assets/img/logo.png
#   feature:
#     tabs: false
#   palette:
#     primary: 'cyan'
#     accent: 'cyan'
#   i18n:
#     prev: 'Previous'
#     next: 'Next'

# copyright: "Copyright &copy; 2016-2019 Al-waleed Shihadeh"

# extra_css:
#   - assets/styles/extra.css
#   - assets/styles/atom-one-light.css

# extra_javascript:
#   - assets/js/hljs/highlight.pack.js
#   - assets/js/extra.js

# plugins:
#   - search
#   - exclude:
#       glob:
#         - "**/include-*.md"

# # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# # https://facelessuser.github.io/pymdown-extensions/
# markdown_extensions:
#   - attr_list
#   - admonition
#   - footnotes
#   - pymdownx.details
#   - pymdownx.inlinehilite
#   - pymdownx.highlight:
#       use_pygments: false
#   - pymdownx.smartsymbols
#   - pymdownx.superfences
#   - pymdownx.tasklist
#   - pymdownx.snippets:
#       check_paths: true
#   - toc:
#       permalink: true

# # Page tree
# nav:
#   - 'Welcome': 'index.md'
#   - 'Ruby Gems':
#       - 'Swarm Orca' : 'ruby-gems/Orca.md'
#       - 'RabbitMQ Client' : 'ruby-gems/RabbitMQ.md'
#       - 'DelayedJob Metrics' : 'ruby-gems/DelayedJobMetrics.md'
#       - 'DeepHealthCheck': 'ruby-gems/DeepHealthCheck.md'